name: flutter_mmnes
description: A new Flutter application # 应用或包的描述、简介
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.

version: 1.0.0+1 # 应用或包的版本号
author: robin pei
homepage: https://github.com/lanhuzi9999

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies: # 应用或包依赖的其它包或插件
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # r日志打印
  log4d: ^1.0.3
  badges: ^1.1.0
  crypto: ^2.0.6
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  # 网络请求库
  dio: ^2.1.13
  #feather_icons_flutter: ^4.7.4
  flutter_html: ^0.10.4
  # 瀑布流
  flutter_staggered_grid_view: ^0.2.7
  # banner
  flutter_swiper: ^1.1.6
  webview_flutter: ^0.3.11+2
  # 图标库中文地址：http://www.fontawesome.com.cn/
  font_awesome_flutter: ^8.4.0
  # 解析html
  html: ^0.14.0+2
  http: ^0.12.0+2
  # 图片选择器
  image_picker: ^0.6.0+15
  # 保存图片
  image_picker_saver: ^0.3.0
  # https://github.com/ReactiveX/rxdart
  rxdart: ^0.22.0

  share: ^0.6.1+1
  # 透明占位图片
  transparent_image: ^0.1.0
  url_launcher: ^5.0.5
  flutter_spinkit: ^2.1.0
  flutter_gallery_assets: 0.1.9+2
  common_utils: ^1.1.1
  # Flutter 全局屏幕适配。https://github.com/flutterchina/auto_size
  # 如果有问题请尝试修改如下链接
  # url: https://github.com/flutterchina/auto_size.git
  auto_size:
    git:
      url: https://github.com/flutterchina/auto_size.git
  fluintl: ^0.1.3
  shared_preferences: ^0.5.3+2
  synchronized: '>=1.5.1 <3.0.0'
  flutter_downloader: ^1.1.7
  permission_handler: ^3.1.0
  path_provider: ^0.5.0
  cached_network_image: ^1.1.0
#  flustars: ^0.2.5+1
dev_dependencies: # 开发环境依赖的工具包（而不是flutter应用本身依赖的包）
  flutter_test:
    sdk: flutter
  #####本地库
  install_apk_plugin:
    path: ./flutter_common_lib/install_apk_plugin
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter. flutter相关的配置选项
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class. https://material.io/tools/icons/?icon=sd_storage&style=baseline
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - images/weather_backgrounds/
    - images/qdaily/
    - assets/data/
    - packages/flutter_gallery_assets/people/ali_landscape.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
          style: italic
          weight: 700

    - family: CustomIcon
      fonts:
        - asset: assets/fonts/custom/iconfont.ttf
          weight: 400

  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages